spring:
  profiles:
    active: enable_async
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      password: ${REDIS_PASSWORD:}

      jedis:
        pool:
          enabled: true
          min-idle: 1

  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    password: ${RABBIT_PASSWORD:guest}
    username: ${RABBIT_USERNAME:guest}

spring-doc:
  swagger-ui:
    operationsSorter: method
  api-docs:
    path: /api-docs

hh:
  base-url: https://api.hh.ru/

