spring:
  data:
    redis:
      host: ${REDIS_HOST}
      password: ${REDIS_PASSWORD}

      jedis:
        pool:
          enabled: true
          min-idle: 1

spring-doc:
  swagger-ui:
    operationsSorter: method
  api-docs:
    path: /api-docs

hh:
  base-url: https://api.hh.ru/

