spring:
  profiles:
    active: enable_async

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      password: ${REDIS_PASSWORD:}

  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    password: ${RABBIT_PASSWORD:guest}
    username: ${RABBIT_USERNAME:guest}

server:
  error:
    include-stacktrace: never

spring-doc:
  swagger-ui:
    path: /swagger-ui
    operationsSorter: method
  api-docs:
    path: /vacancy-service/api-docs

hh:
  base-url: https://api.hh.ru/

